### ISSUE TITLE
How to place car on lane given WorldPosition

### ISSUE THREAD

**Issue by johschmitz** [pyoscx/scenariogeneration#33]
I am wondering how I can find the lane ID given a World Position using only the scenariogeneration lib. Is there any kind of helper function for that? For a two lane road I could use something like:
```
init.add_init_action(car_name, xosc.RelativeLaneChangeAction(0, car_name,
    xosc.TransitionDynamics(xosc.DynamicsShapes.step, xosc.DynamicsDimension.rate, 1)))
```
But without knowing the absolute lane ID it is difficult. So a WorldPosition to RoadPosition or LanePosition would be needed.

Is there any known solution to this problem without using additional libraries?

**Comment by johschmitz** [comment]
Okay I think I was wrong, the relative lane change does indeed for what I want to do also for multiple lanes. However, I just did not configure the width of the lanes correctly with respect to my 3D model and also had a bug in my code.

I am now going with a
```
init.add_init_action(car_name, xosc.RelativeLaneChangeAction(0, car_name,
    xosc.TransitionDynamics(xosc.DynamicsShapes.cubic, xosc.DynamicsDimension.rate, 1.0)))
```
to obtain a smooth transition from the initial position of the car to the center of the current lane.

Nevertheless, I think it would be quite helpful to have some helper function exposed that can convert between the different coordinate systems and helping to find out lane IDs from world coordinates.

**Comment by MandolinMicke** [comment]
I know esmini does this "inherently". But then all lanes are created as separate objects. 

The problem with scenariogeneration is that no such things are done, only the start/endpoint of each geometry, NOT the lanes since their geometry are of no interest for the resulting xodr.

However everything is defined, so all data is there to do it, just quite alot of work to make it work and alot of tests to write (especially when changing the number of lanes on a road, junctions and so on)

**Comment by johschmitz** [comment]
Okay I guess this can be closed then at this point. Hopefully you, me or someone else will find time to implement this at some point in the future.

**Comment by MandolinMicke** [comment]
Agreed, would be pretty good to be able to convert between different systems later on.
