### ISSUE TITLE
OpenSCENARIO 2.0 support 

### ISSUE THREAD

**Issue by dkarunakaran** [pyoscx/scenariogeneration#80]
Any plan to include OpenSCENARIO 2.0 soon?

**Comment by MandolinMicke** [comment]
Hi, good question. 
No, not really. Since that is supposed to be a high level scenario description it "should not be needed".

OpenSCENARIO 1.0 was another story since that is rather low level and xml based, and at that time there was no real way to parametrize and run batch-simulations using OpenSCENARIO (It was introduced in 1.1).

This was created as a way to actually create OpenSCENARIO 1.0 xmls (then grew to OpenDRIVE aswell), and not sit and write in xml (I would never get my users to do that).

**Comment by dkarunakaran** [comment]
Hi, 

Thanks for the insight and publishing this great library.

Regards
